# Generated by Django 4.0.4 on 2022-05-16 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_menu_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Имя категории')),
                ('cat_menu_name_image', models.ImageField(blank=True, null=True, upload_to='image/menu/%Y/%m/%d/', verbose_name='Фото категории меню')),
            ],
        ),
        migrations.CreateModel(
            name='BaseMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_menu', models.CharField(blank=True, max_length=40, null=True, verbose_name='Заголовок меню')),
                ('text_menu', models.TextField(blank=True, null=True, verbose_name='Текст меню')),
                ('image_menu', models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d/', verbose_name='фото')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nomad_Coffee_Naryn_app.catmenu', verbose_name='Категория')),
            ],
        ),
    ]
